---
- name: Add Elasticsearch repository
  yum_repository:
    name: elasticsearch-5.x
    description: Elasticsearch repository for 5.x packages
    baseurl: https://artifacts.elastic.co/packages/5.x/yum
    gpgkey: https://artifacts.elastic.co/GPG-KEY-elasticsearch
- name: Install java
  yum:
    name: java
    state: latest
- name: Add Elasticsearch key to keystore
  rpm_key:
    state: present
    key: https://artifacts.elastic.co/GPG-KEY-elasticsearch
- name: Install Logstash 
  yum:
    name: logstash
    state: latest
  notify: "notify logstash for restart"
