---
- name: Add Elasticsearch repository
  yum_repository:
    name: elasticsearch-5.x
    description: Elasticsearch repository for 5.x packages
    baseurl: https://artifacts.elastic.co/packages/5.x/yum
    gpgkey: https://artifacts.elastic.co/GPG-KEY-elasticsearch
- name: Add Elasticsearch key to keystore
  rpm_key:
    state: present
    key: https://artifacts.elastic.co/GPG-KEY-elasticsearch
- name: Install Logstash 
  yum:
    name: logstash
    state: latest
- name: Configure local log filebeat configuration to test
  template:
    src: filebeat.yml.j2
    dest: /etc/filebeat/filebeat.yml
  notify: "notify filebeat for restart"
- name: Configure local log collection in logstash from filebeat
  template: 
    src: local_logs.conf.j2
    dest: /etc/logstash/conf.d/local_logs.conf
  notify: "notify logstash for restart"
